# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY BussinessTier_Prov/BussinessTier_Prov.csproj BussinessTier_Prov/
RUN dotnet restore BussinessTier_Prov/BussinessTier_Prov.csproj

COPY . .
WORKDIR /src/BussinessTier_Prov
RUN dotnet publish -c Release -o /app/out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://+:8081

EXPOSE 8081
ENTRYPOINT ["dotnet", "BussinessTier_Prov.dll"]
