# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY DataTier_Prov/DataTier_Prov.csproj DataTier_Prov/
RUN dotnet restore DataTier_Prov/DataTier_Prov.csproj

COPY . .
WORKDIR /src/DataTier_Prov
RUN dotnet publish -c Release -o /app/out

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 8080
ENTRYPOINT ["dotnet", "DataTier_Prov.dll"]
